// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCta02bRHmb_6Xu_LHS-qdYfcSSRASWeQk',
    appId: '1:103108297358:web:7690edb5bbc4bc3ae37fdf',
    messagingSenderId: '103108297358',
    projectId: 'iot-health-monitor-c3c26',
    authDomain: 'iot-health-monitor-c3c26.firebaseapp.com',
    storageBucket: 'iot-health-monitor-c3c26.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBu0xjq6TsVlovfluJsUkw69bBu-TxbntQ',
    appId: '1:103108297358:android:1bf71d4814e5b1e3e37fdf',
    messagingSenderId: '103108297358',
    projectId: 'iot-health-monitor-c3c26',
    storageBucket: 'iot-health-monitor-c3c26.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnT7Zy5DoA4fakANbeZajddG_mBqUtFQg',
    appId: '1:103108297358:ios:a52eba14f923e26fe37fdf',
    messagingSenderId: '103108297358',
    projectId: 'iot-health-monitor-c3c26',
    storageBucket: 'iot-health-monitor-c3c26.firebasestorage.app',
    iosBundleId: 'com.example.iotControlApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAnT7Zy5DoA4fakANbeZajddG_mBqUtFQg',
    appId: '1:103108297358:ios:a52eba14f923e26fe37fdf',
    messagingSenderId: '103108297358',
    projectId: 'iot-health-monitor-c3c26',
    storageBucket: 'iot-health-monitor-c3c26.firebasestorage.app',
    iosBundleId: 'com.example.iotControlApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCta02bRHmb_6Xu_LHS-qdYfcSSRASWeQk',
    appId: '1:103108297358:web:46e1d32c44ffc692e37fdf',
    messagingSenderId: '103108297358',
    projectId: 'iot-health-monitor-c3c26',
    authDomain: 'iot-health-monitor-c3c26.firebaseapp.com',
    storageBucket: 'iot-health-monitor-c3c26.firebasestorage.app',
  );
}
